drop table if exists coverletters CASCADE;

CREATE TABLE users (
    userId VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE coverletters (
    coverLetterId LONG generated by default as identity,
    userId VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    uploadDate Date,
<<<<<<< HEAD
    content VARCHAR(255) NOT NULL,
    PRIMARY KEY (coverLetterId)
);
=======
    content VARCHAR(255) NOT NULL
);

CREATE TABLE questions (
    id Long AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255),
    ques VARCHAR(MAX)
);
>>>>>>> 68476b2780477de115886d7b28d5769db1999599
