drop table if exists users CASCADE;
drop table if exists coverletters CASCADE;
drop table if exists questions CASCADE;

CREATE TABLE users (
    userId VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE coverletters (
    coverLetterId LONG generated by default as identity,
    userId VARCHAR(255),
    title VARCHAR(255) NOT NULL,
    uploadDate Date,
    content VARCHAR(255) NOT NULL,
    PRIMARY KEY (coverLetterId)
);

CREATE TABLE questions (
    quesId Long generated by default as identity,
    userId VARCHAR(255),
    ques VARCHAR(MAX),
    PRIMARY KEY (quesId)
);